---
title: "Математические методы и модели"
subtitle: "Описание и программа курса"
author: "Храмов Д.А."
date: "04.02.2019"
output: 
  html_document:
    toc: true
---

Наш курс знакомит с применением информационных технологий в естественных науках, с так называемыми "научными вычислениями" (scientific computing).

Все мы используем результаты этих вычислений, по крайней мере, в виде готовых программ и библиотек. Основу их составляют математические модели, процесс разработки и применения которых рассматривается в данном курсе. Из каких элементов должна состоять модель, чтобы ею можно было воспользоваться? Какую модель выбрать в конкретной ситуации? На какую точность мы можем рассчитывать? Каковы ограничения на применение модели? Ответив на эти вопросы, мы сможем грамотно использовать имеющиеся в нашем распоряжении программные средства.

Одновременно с рассмотрением самих моделей, мы попытаемся проследить за их эволюцией, и тем, какую роль играет в этом совершенствование информационных технологий.

Кроме того, наш курс служит ступенькой для освоения других курсов: основ языка Matlab, численных методов и методов оптимизации.


## 1. Модель и моделирование

Что такое модель и моделирование. Зачем нужны модели. Какими бывают модели. 
Процесс принятия решений и место моделирования в нем. Постановка цели.

Что нового привносит в моделирование компьютер.

Особенности машинной арифметики. Некоммутативность сложения и другие проблемы. Представление действительных чисел на компьютере. Примеры проблем, вызванных ошибками округления.

**Задачи.** Решение уравнения графическим способом.


## 2. Этапы моделирования. Обыкновенные дифференциальные уравнения

Процесс построения модели. Модель народонаселения Мальтуса. Перечень допущений — неотъемлемая составляющая модели. 

Недостатки разностной модели. Переход от разностной модели к обыкновенному дифференциальному уравнению (ОДУ). Аналитическое решение. Символьные решения в Matlab. Что дает знание аналитического решения.

Исследование при помощи модели. Основные этапы исследования. Недостатки модели Мальтуса и возможности ее развития. Емкость среды. Модель Ферхюльста.

Пример моделирования колебаний груза на пружине.

**Задачи.** Поиск аналитического решения дифференциального уравнения.


## 3. Численное решение дифференциальных уравнений

Метод Эйлера. Локальная и общая ошибки. Причины возникновения ошибок. Точность метода Эйлера. Реализация метода Эйлера на языке Matlab (модель Мальтуса). Проблемы метода Эйлера: малая точность, неустойчивость. Поиски выхода. Модифицированный метод Эйлера.

Решатели ОДУ в Matlab. Приведение ОДУ к каноническому виду.

**Задачи.** Численное решение ДУ методом Эйлера и сравнение результата с аналитическим рещением.


## 4. Методы Монте-Карло

Статистические испытания. Генератор случайных чисел. Вычисление интегралов. Вычисление числа "пи". Вычисление экстремумов. Моделирование диффузии. 

Калибровка модели. Задача об остывании чашки кофе: подбор коэффициента остывания.

**Задачи.** ВЫчисление интеграла методом Монте-Карло.


## 5. Метод наименьших квадратов

Метод наименьших квадратов (МНК). Задача об остывании чашки кофе возвращается: подбираем коэффициент остывания с помощью МНК. Аппроксимация функций, ее разновидности. Реализация в Matlab (интерполяция: polyfit, семейство interp*; МНК: fit из Curve Fitting Toolbox).

Прогнозирование (регрессия) и аппроксимация: сравнение задач. Проблема переподгонки. Обобщающая способность модели. Кросс-валидация (перекрестная проверка).

**Задачи.** Аппроксимация данных кубическим многочленом.


## 6. Клеточные автоматы и агентное моделирование

Идея: если аналитического решения ДУ нет, можно сразу создавать модель из малых, но конечных фрагментов. Клеточные автоматы (КА). Моделирование диффузии. Одномерные КА. Правило 30. Игра "Жизнь".

Агентное моделирование. Агент и правила. Роевой интеллект. Муравьиные алгоритмы. Boids.

Добавляем пространственные измерения. Построение модели (уравнение диффузии). Аналитическое решение. Что делать, если аналитического решения нет. Метод конечных разностей. Программа на Matlab'е. 


## 7. Сетевое планирование

Сетевое планирование — инструмент управления проектами. Графы и сетевые графики. Построение сетевого графика проекта. Поиск критического пути. Какие задачи позволяет решить сетевой график. Диаграмма Гантта.

**Задачи.** Построение сетевого графика. Определение длительности выполнения проекта и критических работ.


## Литература

1. Бёрд Дж. Инженерная математика: Карманный справочник. — М.: Издательский дом «Додэка-ХХI», 2008.
2. Мышкис А. Д. Элементы теории математических моделей. 3-е изд., испр. М.: КомКнига, 2007. — 192 с.
3. Поршнев С. В. Вычислительная математика. Курс лекций. — СПб.: БХВ-Петербург, 2004.
4. Поршнев С. В. Компьютерное моделирование физических процессов в пакете MATLAB: Учебное пособие. 2-е изд., испр. — СПб.: Издательство «Лань», 2011.
